![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [13]:
my_array = np.arange(0,10)
print(my_array.where())


[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:
print(my_array[7],my_array[8])
print(np.split(my_array,[7,8]))

7 8
[array([0, 1, 2, 3, 4, 5, 6]), array([7]), array([8, 9])]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [112]:
matrix_4 = np.arange(1,21).reshape(4,5)
print(matrix_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [113]:
np.flip(matrix_4)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [115]:
print(matrix_4)
matrix_4[::-1, ::-1]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [9]:
matrix_4[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [110]:
print(matrix_4[::2, ::2])


[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [35]:
np.flip(matrix_4[:3,], axis=1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [118]:
print(matrix_4)
matrix_4[:3:, ::-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [106]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x_bools = np.array(x == "Loro")
print(x_bools)
print(x[x_bools])

[ True False False  True False]
['Loro' 'Loro']


In [109]:
x_2 = np.where(x == 'Loro', x, None)
print(x_2)

['Loro' None None 'Loro' None]


[ True False False  True False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [41]:
ejer_9 = np.arange(0,20)
print(ejer_9)
print(ejer_9.reshape(2,5,2))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [42]:
np.flip(matrix_4)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [119]:
print(matrix_4[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [48]:
ejer_11 = np.array([0., 0., 0., 0., 0.,0., 0., 0., 0., 0.])

print(ejer_11.nbytes)
print(ejer_11.itemsize)


80
8


In [49]:
ejer_11[4] = 1
print(ejer_11)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [121]:
ejer_12 = np.arange(10,50)
print(ejer_12)

print(np.flip(ejer_12))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [122]:
print(ejer_12[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [40]:
vector = np.array([1,2,0,0,4,0])
vector_bool = np.array(vector != 0)
print(vector_bool)

print(vector[vector_bool])



indices = np.where(vector_bool)
print(indices)

[ True  True False False  True False]
[1 2 4]
(array([0, 1, 4], dtype=int64),)


[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [11]:
ejer_14 = np.random.random(size=(10,10))
print(ejer_14)
print(np.min(ejer_14))
print(np.max(ejer_14))


[[0.62977466 0.48077382 0.6210601  0.51080073 0.33160067 0.69067143
  0.32086426 0.1520666  0.50061923 0.26463081]
 [0.40956114 0.6214145  0.99398781 0.47722491 0.99276952 0.99131834
  0.89593888 0.75353394 0.05087416 0.75995434]
 [0.6620309  0.62278632 0.71886092 0.02839816 0.84363239 0.69500668
  0.33137375 0.93751724 0.90108481 0.54384399]
 [0.95136612 0.05780068 0.85273112 0.97634886 0.09974086 0.97139095
  0.92382329 0.82635688 0.18550404 0.44483843]
 [0.92625054 0.58333352 0.35937287 0.02156458 0.76267691 0.51095315
  0.40025958 0.90026983 0.76912267 0.6791173 ]
 [0.45303639 0.89729082 0.05903888 0.08494569 0.94937229 0.6939295
  0.64683898 0.79980693 0.4859207  0.18996045]
 [0.94766474 0.46237991 0.78967129 0.43149559 0.17954927 0.10476763
  0.92693658 0.82383164 0.68129846 0.31632019]
 [0.08854565 0.75482141 0.8164123  0.61367376 0.33302153 0.45377495
  0.63342073 0.70623472 0.72639028 0.91948573]
 [0.45945524 0.68750474 0.08862516 0.27004495 0.28761654 0.10937855
  0.41229175 

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [14]:
ejer_15 = np.random.random(size=30)
print(ejer_15)
np.mean(ejer_15)

[0.01709678 0.87136055 0.13689801 0.35059067 0.98750457 0.43959714
 0.54753899 0.20279982 0.44074673 0.75469318 0.22376464 0.99321769
 0.57502155 0.99049244 0.43511551 0.35817379 0.60204159 0.34961546
 0.60252857 0.93147724 0.45443966 0.35024278 0.18210751 0.34042184
 0.91881332 0.52919864 0.83806475 0.41526908 0.48900024 0.73226098]


0.535336456740514

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [26]:
matrix_16 = np.ones((6,6), np.int32)
print(matrix_16)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [28]:
matrix_16[1:5,1:5] = 0
print(matrix_16)

# matrix_16.itemset((1:5,1:5), 0)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

AxisError: axis 1 is out of bounds for array of dimension 1

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [49]:
array_18 = np.array(([0, 1],[1, 0]))
ejer_18 = np.tile(array_18, (4,4))
print(ejer_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

[[ 8  1  2  1 14]
 [ 9 10  5 14 16]
 [11 10  5 19 10]
 [19 14 19 11 15]
 [ 6 13 12 12  1]]
[[-0.41709302 -1.69764177 -1.51470623 -1.69764177  0.68052019]
 [-0.23415749 -0.05122195 -0.96589963  0.68052019  1.04639126]
 [ 0.13171359 -0.05122195 -0.96589963  1.59519787 -0.05122195]
 [ 1.59519787  0.68052019  1.59519787  0.13171359  0.86345573]
 [-0.78296409  0.49758466  0.31464912  0.31464912 -1.69764177]]


[[20 24  8  1 28]
 [29  2  1 26 14]
 [ 9 10 29 28  5]
 [29 14 16 11 27]
 [10  5 21 19 10]]
[[18  2 22 11 11]
 [10 22 28  8 23]
 [26 10 13 23 19]
 [29  4 20  4 21]
 [ 1  3  6 20 13]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [67]:
ejer_20 = np.arange(0,11)
print(ejer_20)

new_20 = ejer_20.copy()
for i in new_20:
    if i>= 3 and i <= 8:
        new_20[i] = -1
print(new_20)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [68]:
new_20_2 = ejer_20.copy()
for i in new_20_2:
    if i>= 3 and i <= 8:
        new_20_2[i] = -i
print(new_20_2)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [93]:
array_inicio = np.array(' ')
tablero = np.tile(array_inicio,(10,10))
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [94]:
tablero[(0,1), (1,1)] = 'O'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [95]:
tablero[1,3:7] = 'O'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [96]:
tablero[1,1] = 'X'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [97]:
tablero[6,8] = '-'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' '-' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' ' ' ' ' ' ']
 [' ' ' ' '-' ' ' ' ' 'O' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
